REPO_PATH=../..
include $(REPO_PATH)/resources/common.mk

MODULE_NAME = char_gen_top
SV_FILES = char_gen_top.sv ../char_gen/char_gen.sv ../char_gen/font_rom.sv ../../lab_multiseg/seven_segment4/seven_segment4.sv ../../lab_sevenseg/seven_segment/seven_segment.sv ../../lab_vga/vga_timing/vga_timing.sv ../../lab_rx/rx/rx.sv ../../lab_debounce/debounce/debounce.sv



