REPO_PATH=../..
include $(REPO_PATH)/resources/common.mk

SYNTH_PARAMS = FILENAME=../../background.mem
MODULE_NAME = codebreaker_top
SV_FILES = ../../text_rendering/char_gen/char_gen.sv ../../text_rendering/char_gen/font_rom.sv ../../multi_segment/seven_segment4/seven_segment4.sv ../../seven_segment/seven_segment/seven_segment.sv ../../video_signal/vga_timing/vga_timing.sv ../../serial_rx/rx/rx.sv ../decrypt_rc4/decrypt_rc4.sv ../write_vga/write_vga.sv ../codebreaker/codebreaker.sv codebreaker_top.sv




