REPO_PATH=../../..
include $(REPO_PATH)/resources/common.mk

MODULE_NAME = rx_top
SV_FILES = rx_top.sv ../rx/rx.sv ../../multi_segment/seven_segment4/seven_segment4.sv ../../seven_segment/seven_segment/seven_segment.sv
