REPO_PATH=../..
include $(REPO_PATH)/resources/common.mk

MODULE_NAME = project_top
SV_FILES = project_top.sv ../pong/pong.sv ../v_line_drawer/v_line_drawer.sv ../ball_drawer/ball_drawer.sv ../bitmap_mem/bitmap_mem.sv ../../common_modules/video_signal/vga_timing/vga_timing.sv ../../common_modules/multi_segment/seven_segment4/seven_segment4.sv ../../common_modules/seven_segment/seven_segment/seven_segment.sv
