REPO_PATH=../..
include $(REPO_PATH)/resources/common.mk

MODULE_NAME = project_top
SV_FILES = project_top.sv ../../common_modules/audio_passthrough/audio_passthrough_top.sv ../../common_modules/audio_passthrough/audio_passthrough_core.sv ../../common_modules/audio_passthrough/audio_clock_mmcm.sv ../../common_modules/audio_passthrough/pmod_i2s2_engine.sv ../../common_modules/audio_passthrough/reset_sync.sv
