REPO_PATH=../..
include $(REPO_PATH)/resources/common.mk

SYNTH_PARAMS = FILENAME=../../background.mem
MODULE_NAME = codebreaker_top
SV_FILES = ../../lab_char/char_gen/char_gen.sv ../../lab_char/char_gen/font_rom.sv ../../lab_multiseg/seven_segment4/seven_segment4.sv ../../lab_sevenseg/seven_segment/seven_segment.sv ../../lab_vga/vga_timing/vga_timing.sv ../../lab_rx/rx/rx.sv ../decrypt_rc4/decrypt_rc4.sv ../write_vga/write_vga.sv ../codebreaker/codebreaker.sv codebreaker_top.sv




