REPO_PATH=../..
include $(REPO_PATH)/resources/common.mk

MODULE_NAME = regfile_top
SV_FILES = regfile_top.sv ../reg4/reg4.sv ../regfile/regfile.sv ../../common_modules/seven_segment/seven_segment_top/seven_segment_top.sv ../../common_modules/seven_segment/seven_segment/seven_segment.sv
