REPO_PATH=..
include $(REPO_PATH)/resources/common.mk

MODULE_NAME = audio_fft_vga_top
SV_FILES = audio_fft_vga_top.sv i2s2_adc_receiver.sv i2s2_dac_transmitter.sv audio_echo_reverb.sv goertzel_spectrum.sv spectrum_vga_renderer.sv ../common_modules/video_signal/vga_timing/vga_timing.sv
