REPO_PATH=..
MODULE_NAME = audio_fft_vga_top
SV_FILES = audio_fft_vga_top.sv i2s2_adc_receiver.sv mini_spectrum_analyzer.sv spectrum_vga_renderer.sv ../common_modules/video_signal/vga_timing/vga_timing.sv

include $(REPO_PATH)/resources/common.mk
