REPO_PATH=../..

MODULE_NAME = project_top
SV_FILES = project_top.sv ../pong/pong.sv ../v_line_drawer/v_line_drawer.sv ../ball_drawer/ball_drawer.sv ../bitmap_mem/bitmap_mem.sv ../../video_signal/vga_timing/vga_timing.sv ../../multi_segment/seven_segment4/seven_segment4.sv ../../seven_segment/seven_segment/seven_segment.sv

include $(REPO_PATH)/resources/common.mk