REPO_PATH=../..
include $(REPO_PATH)/resources/common.mk

MODULE_NAME = debounce_top
SV_FILES = debounce_top.sv ../debounce/debounce.sv ../../lab_multiseg/seven_segment4/seven_segment4.sv ../../lab_sevenseg/seven_segment/seven_segment.sv
