REPO_PATH=../..
include $(REPO_PATH)/resources/common.mk

MODULE_NAME = char_gen_top
SV_FILES = char_gen_top.sv ../char_gen/char_gen.sv ../char_gen/font_rom.sv ../../common_modules/multi_segment/seven_segment4/seven_segment4.sv ../../common_modules/seven_segment/seven_segment/seven_segment.sv ../../common_modules/video_signal/vga_timing/vga_timing.sv ../../serial_rx/rx/rx.sv ../../common_modules/debounce/debounce/debounce.sv



